name: "getData"
permissions:
  contents: write
on:
  schedule:
    - cron: "5,35 * * * *"
  workflow_dispatch:
jobs:
  run-getter:
    runs-on: ubuntu-latest
    steps:
      - name: setpermission
        uses: actions/checkout@v4

      - name: build node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: install
        run: |
          npm install playwright
          npx playwright install chromium --with-deps
      - name: run index
        run: node index.js
      - name: commit and push
        run: |
          git config --local user.email "github-action[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data.json
          git commit -m "chore: update data [skip ci]" || exit 0
          git push
